language: java
jdk:
- oraclejdk7
sudo: false
env:
  global:
  - secure: B6ckh2pJYwvbyjWOoWmMar8X9uwbVORDXjT0XBl5BIUNW1NwARpTyWm6hpjAFqoMu7P/JTOQHBIRl5CNHGC/1W09Viy6RZ9TNT6qyZJWr1ArwqxxXATwLK32QUq48ETVBOA3XLFQcwSN+sRu1obBuXQfIbC0sLrO9ITarpS6QJg=
after_success:
- chmod +x ./deploy.sh; ./deploy.sh
