language: java
jdk:
- oraclejdk8
env:
  global:
  - secure: CEtTDSmSgzlYhysz1Nkg5Sx9PpvSS2FMq7KIHm7fGsZubWOuQmX/yBZBuTyV3KNKadWWyT9zh/zHZsF+U+NBsFg7kRBk44U4ZZfuKW3LbdTNjcWLyo/XK8SOyg6r69fLIT0pg5fKLYYXYXGKGKR0waPM6iFlp60AEfZpQ9ZfU9w=
  - secure: WvTZK86timtWz4qQRXTPhDhK+F28X8k51rw3wZ3AgLJAFkfaQVRJ1CbpZowTZpQx1aMOHG7reRAvEgDPdd+GegCXhDNdX9MWfALpW8fVZNbZYCGpsuONDT75YxN06dKv7qaDGrNCY3ktkii3x36BqWmvg5t1FXz48dkrwwxEnhY=
after_success:
- chmod +x ./deploy.sh; ./deploy.sh
